service: iudex

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1
  profile: nymun

functions:
  auth:
    name: auth
    handler: handler.auth
    events:
      - schedule: rate(1 minute)
      - http:
          path: auth
          method: POST
          cors: true
    
